# Generated by Django 3.0.6 on 2020-06-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
